### PR TITLE
Have made cross origin login fix

### LINKED ISSUE #283: haveMadeCrossOriginLogin_ in URL
See https://forum.image.sc/t/omero-iviewer-a-strage-url-change-when-clicked-on-a-thumbnail/30260

haveMadeCrossOriginLogin_ is a flag used when running the development server and shouldn't be seen on released iviewer.

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #283 

To test:
 - Use Open-With to open iviewer - this gives URL like https://merge-ci.openmicroscopy.org/web/iviewer/?images=18189
 - Click on another thumbnail to show another Image. The URL updates
 - The URL should not contain the ```haveMadeCrossOriginLogin_``` flag

### CODE REVIEW

**Comment by pwalczysko** [comment]
Looks good to me. 
Ready to merge FMPOV

File: src/main.js [hunk 1]
```diff
@@ -38,21 +38,7 @@ require('../css/app.css');
...
 let req = window.INITIAL_REQUEST_PARAMS || {};
-let is_dev_server = false;
-// #if process.env.NODE_ENV === 'dev-server'
-is_dev_server = true;
-// #endif
-if (!is_dev_server) {
-    let prefix =
-        typeof req[URI_PREFIX] === 'string' ?
-            Misc.prepareURI(req[URI_PREFIX]) : "";
-    __webpack_public_path__ = prefix + '/static/' + PLUGIN_NAME + '/';
```
Comment (joshmoore) [inline src/main.js]: In general, it seems like you've stripped things out regarding for when `dev_server` is true which seems safe enough, but isn't this clause for the _non_-`dev_server` case?

Comment (will-moore) [reply src/main.js]: I don't fully understand all of the use cases here, but as far as I can see, this code was hard-coded NOT to run (since ```is_dev_server = true;``` came right before that if).
So I don't know when that code has ever run.
It's only job is to set ```__webpack_public_path__``` .Webpack dev server isn't used in production. Webpack is used to package the JS bundle, but we've been doing that a lot without this code, so I can only assume this isn't needed in our current workflows.

Comment (joshmoore) [reply src/main.js]: _Urgh_. Thanks for the cleanup :+1:

Comment (joshmoore) [reply src/main.js]: see https://github.com/ome/omero-iviewer/pull/142 for the introduction of this.

**Comment by joshmoore** [comment]
Merging and leaving someone else to suggest release.
